# Generated by Django 4.2 on 2025-01-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_alter_activity_category_alter_activity_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='admin_side.destination'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activity/'),
        ),
    ]
