# Generated by Django 4.2 on 2025-01-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0004_alter_accommodation_destination_alter_activity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='destination',
        ),
    ]
