# Generated by Django 4.2 on 2025-01-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0005_remove_activity_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='article',
            name='destination',
        ),
    ]
