# Generated by Django 4.2 on 2025-01-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0007_destination_latitude_destination_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'ordering': ['-rating'], 'verbose_name_plural': 'Accommodations'},
        ),
        migrations.AddField(
            model_name='activity',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
