# Generated by Django 4.2 on 2025-01-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0008_alter_accommodation_options_activity_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='menu_url',
            new_name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='price_range',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
