# Generated by Django 4.2 on 2025-01-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0009_rename_menu_url_restaurant_facebook_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine_type',
        ),
    ]
