# Generated by Django 4.2 on 2025-01-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0010_remove_restaurant_cuisine_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='photo',
            new_name='image',
        ),
    ]
