# Generated by Django 4.2 on 2025-01-18 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0011_rename_photo_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(choices=[('beach', 'Beach'), ('travel', 'Travel'), ('cultural', 'Cultural'), ('activty', 'Activity')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
