# Generated by Django 4.2 on 2025-01-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0014_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('accommodation', 'Accommodation'), ('activities', 'Activities'), ('food_drinks', 'Food & Drinks'), ('destination', 'Destination'), ('articles', 'Articles')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Chat Inquiries',
            },
        ),
    ]
