# Generated by Django 4.2.7 on 2025-01-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_uploadedfile_description_uploadedfile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
